version: '3.8'

services:
    web:
      container_name: flask
      build: .
      restart: always
      expose:
        - 5000
      volumes:
        - .:/imse_m2_team27

    db:
      image: mysql:5.7
      restart: always
      container_name: sql
      environment:
        MYSQL_DATABASE: imse_m2_db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
      expose:
        - 3306
      volumes:
        - db:/var/lib/mysql

    mongodb:
      image: mongo
      restart: always
      container_name: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: imse_m2_mongo
      #expose:
       # - 27017
      ports:
        - "27017:27017"

    nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      ports:
        - "5000:8000"
        - "443:443"
      volumes:
        - ./nginx/certs:/etc/nginx/certs
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

volumes:
  db:
    driver: local
