version: "3.8"
services:
  mysql:
    build: ./mysql
    networks:
        sql-server:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ise-database
      MYSQL_USER: ise-user
      MYSQL_PASSWORD: password
    restart: always
    
  web:
    build: ./web
    networks:
        sql-server:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ise-database
      MYSQL_USER: ise-user
      MYSQL_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - mysql
    restart: on-failure
    
networks:
    sql-server:
    